name: CD
on:
  push

jobs:
  test:
    uses: ./.github/workflows/ci-tpl-gradle.yml
    with:
      gradle_command: test

  build:
    needs: test
    uses: ./.github/workflows/ci-tpl-gradle.yml
    with:
      gradle_command: build