name: CD
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/run-gradle
        with:
          gradle_command: test

      - uses: ./.github/actions/run-gradle
        with:
          gradle_command: build