name: CD
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/run-gradle
        with:
          gradle_command: test

      - name: Build
        uses: ./.github/actions/run-gradle
        with:
          gradle_command: build